#################################################################
# PHP dev environment with Apache, MariaDB and phpMyAdmin
#
# @author: Vanessa Richie Alia-Trapero <vrat.engr@gmail.com>
#################################################################

# this is optional and for info purposes only, not a basis for this file
version: '3.8'

# list of containers
services:
    db: # service name for our database and can be customized per your setup
      container_name: db-container # <container-name>
      image: mariadb:11.0 # https://hub.docker.com/_/mariadb
      restart: always # restarts the service whenever any defined configuration changes 
      networks:
        - app-network # <network-name>
      # ports:
      #   - 9906:3306
      volumes:
        - ./config/db:/docker-entrypoint-initdb.d/ # <source folder>:/docker-entrypoint-initdb.d/ - this will dump all the .sql or tar files in source folder
        - dbdata:/var/lib/mysql # <volume name>:<mapped location within the container>
      environment:
        MARIADB_ROOT_PASSWORD : root # <root-password>
        MARIADB_DATABASE: mydb # <database-name>
        MARIADB_USER : user # <database-user>
        MARIADB_PASSWORD : user # <user-password>

    app: # service name for our web server and php
      container_name: php-apache
      restart: always
      networks:
        - app-network
      ports:
        - 8080:80 # map TCP port 80 to xxxx
        - 444:443 # map SSL port 443 to xxx
      volumes:
        - ./html:/var/www/html # ./<source code directory>:<apache web directory within the container> - this is a two-way binding, so what happens in the container happens in the source
      depends_on:
        - db # <service name for our database> - this is to specify dependency/requirements, our app requires the db container for it to work
      build: # there may be cases where you need to customize an image from Docker Hub, so instead of specifying an image for this service, we will define the image via the Dockerfile
        context: . # path to where the Dockerfile resides
        dockerfile: Dockerfile # name of the Dockerfile, default is Dockerfile, you can omit this if you follow the standard naming
      extra_hosts:
        - "vratengr.com:127.0.0.1" # this adds an entry in /etc/hosts

    phpmyadmin: # optional if you want to have GUI for your database
      container_name: db-gui
      image: phpmyadmin:5.2.1
      restart: always
      networks:
        - app-network
      ports:
        - 8082:80
      depends_on:
        - db

networks: # an app usually needs multiple services to function, defining a network groups these services to create the app environment
  app-network:

volumes: # we are going to persist the db data using volumes so that even if you stop the container, the data will persist within docker
  dbdata: