CREATE TABLE IF NOT EXISTS `notes` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
    `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `last_modified` DATETIME on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `note` TEXT NOT NULL ,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;